### PR TITLE
fix compatibility of OpenFOAM easyblock with --module-only

### PR DESCRIPTION
**Pull request by boegel**
for https://github.com/hpcugent/easybuild-easyblocks/pull/784

This is required to make sure that the value of `self.wm_compiler`, which is used during the sanity check, is defined correctly; without this `--module-only` for OpenFOAM fails because it generates a value like `linux64NoneDPOpt`

### CODE REVIEW

**Comment by wpoely86** [comment]
what about the others? `WM_LABEL_SIZE`, `WM_MPLIB` etc

**Comment by boegel** [comment]
@wpoely86 only `self.openfoamdir` (which is defined by the constructor) and `self.wm_compiler` are using in the sanity check (not `$WM_COMPILER`, that is still set by the `configure_step`, as it should be)

**Comment by boegel** [comment]
@wpoely86 ah, hold on... you're talking about the env vars being used by `make_module_extra`....

**Comment by boegel** [comment]
@wpoely86 issue fixed for `WM_MPLIB`; for `WM_LABEL_SIZE` and the others there is no problem since `make_module_extra` doesn't depend on `self.wm*`

**Pull request merged**
